paths:
  base_dir: ${BASE_DIR}

service:
  port: 4100
  host: 0.0.0.0

cors:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - DELETE
    - OPTIONS
  allow_headers:
    - Content-Type
    - Authorization
  expose_headers:
    - Content-Type
  supports_credentials: false
  max_age: 3600
